const clothes = [
    {
        "_id": 1,
        "name": "LICRAS GYMSHARK",
        "imgprincipalUrl": "img/licragymsharkseis.png",
        "price": 9000,
        "stock": "Disponible",
        "description": "Licras gymshark 6 colores, tela tipo brush no transparentan ajustada al contorno del cuerpo",
        "imgsecundary": "img/licragymsharkseis.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "6 COLORES",
        "talla": " S M L",
        "categories": ["Mas vendidos", "licras", "gymshark", "mujer"]
    },
    {
        "_id": 2,
        "name": "DUOS DEPORTIVOS",
        "imgprincipalUrl": "img/DUOSNIKE5.png",
        "price": 10000,
        "stock": "Disponible",
        "description": "Duos deportivos NIKE licra corta, 5 colores, tela brush no transparentan y ajustada al contorno del cuerpo",
        "imgsecundary": "img/DUOSNIKE5.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "5 COLORES",
        "talla": " S M L",
        "categories": ["Mas vendidos", "Duos Deportivos", "nike", "mujer"]
    },
    {
        "_id": 3,
        "name": "SET NIKE",
        "imgprincipalUrl": "img/setnike8piezas.png",
        "price": 22900,
        "stock": "Disponible",
        "description": " el mejor Set nike color negro  8 piezas , tela brush no transparentan y ajustada al contorno del cuerpo",
        "imgsecundary": "img/setnike8piezas.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "8 PIEZAS",
        "talla": " S M L",
        "categories": ["Mas vendidos", "SETS", "nike", "mujer"]
    },
    {
        "_id": 4,
        "name": "SET GYMSHARK",
        "imgprincipalUrl": "img/gymshark5piezas 2.png",
        "price": 17500,
        "stock": "Disponible",
        "description": "Set gymshark color negro y blanco  5 piezas , tela brush no transparentan y ajustada al contorno del cuerpo",
        "imgsecundary": "img/gymshark5piezas 2.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "5 PIEZAS",
        "talla": " S M L",
        "categories": ["Mas vendidos", "SETS", "gymshark", "mujer"]
    },
    {
        "_id": 5,
        "name": "GORRA GYMSHARK W",
        "imgprincipalUrl": "img/gorragymsharkw.png",
        "price": 9000,
        "pricepromo": 13000,
        "stock": "Disponible",
        "description": "Gorra gymshark blanca,con ajuste personalizado, combina el estilo y entrenamiento",
        "imgsecundary": "img/gorragymsharkw.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "Color Blanco",
        "talla": " Unica",
        "categories": ["Promocion", "Accesorios", "gymshark", "Gorra"]
    },
    {
        "_id": 6,
        "name": "DUO DEPORTIVO NIKE",
        "imgprincipalUrl": "img/duoslicralarga.png",
        "price": 11000,
        "pricepromo": 15000,
        "stock": "Disponible",
        "description": "duo deportivo nike licra larga , diferentes opciones a escojer tela brush",
        "imgsecundary": "img/duoslicralarga.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "LICRA LARGA S M L",
        "talla": " Unica",
        "categories": ["Promocion", "Duos Deportivos", "nike", "mujer"]
    },
    {
        "_id": 7,
        "name": "DUO OVERZIZE pink BIKER",
        "imgprincipalUrl": "img/bikerduorosado.png",
        "price": 12000,
        "pricepromo": 17000,
        "stock": "Disponible",
        "description": "duo deportivo licra biker rosado , tela brush",
        "imgsecundary": "img/bikerduorosado.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "S M L",
        "talla": " S M L",
        "categories": ["Promocion", "Duos Deportivos", "mujer"]
    }

]