const clothes = [
    {
        "_id": 1,
        "name": "LICRAS GYMSHARK",
        "imgprincipalUrl": "img/licragymsharkseis.png",
        "price": 9000,
        "stock": "Disponible",
        "description": "Licras Gymshark en 6 colores. Hechas de tela tipo brush, estas licras se ajustan perfectamente al contorno del cuerpo y no son transparentes, ofreciendo comodidad y estilo durante tus entrenamientos.",
        "imgsecundary": "img/setnike8piezas.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "6 COLORES",
        "talla": ["S", "M", "L"],
        "categories": ["MAS VENDIDOS", "LICRAS", "GYMSHARK", "MUJER"]
    },
    {
        "_id": 2,
        "name": "DUOS DEPORTIVOS",
        "imgprincipalUrl": "img/DUOSNIKE5.png",
        "price": 10000,
        "stock": "Disponible",
        "description": "Duos deportivos Nike en licra corta, disponibles en 5 colores. Fabricados con tela brush, estos conjuntos son ideales para un ajuste perfecto y total comodidad durante tus actividades físicas.",
        "imgsecundary": "img/setnike8piezas.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "5 COLORES",
        "talla": ["S", "M", "L"],
        "categories": ["MAS VENDIDOS", "DUOS DEPORTIVOS", "NIKE", "MUJER"]
    },
    {
        "_id": 3,
        "name": "SET NIKE",
        "imgprincipalUrl": "img/setnike8piezas.png",
        "price": 22900,
        "stock": "Disponible",
        "description": "Set Nike de color negro compuesto por 8 piezas. Hecho de tela brush, este set está diseñado para ofrecerte un ajuste cómodo y estilizado, ideal para cualquier actividad deportiva.",
        "imgsecundary": "img/gymshark5piezas 2.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "8 PIEZAS",
        "talla": ["S", "M", "L"],
        "categories": ["MAS VENDIDOS", "SETS", "NIKE", "MUJER"]
    },
    {
        "_id": 4,
        "name": "SET GYMSHARK",
        "imgprincipalUrl": "img/gymshark5piezas 2.png",
        "price": 17500,
        "stock": "Disponible",
        "description": "Set Gymshark de color negro y blanco, compuesto por 5 piezas. Fabricado con tela brush que no transparenta, este set ofrece un ajuste perfecto y un estilo atractivo para tus entrenamientos.",
        "imgsecundary": "img/setnike8piezas.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "5 PIEZAS",
        "talla": ["S", "M", "L"],
        "categories": ["MAS VENDIDOS", "SETS", "GYMSHARK", "MUJER"]
    },
    {
        "_id": 5,
        "name": "GORRA GYMSHARK W",
        "imgprincipalUrl": "img/gorragymsharkw.png",
        "price": 9000,
        "pricepromo": 5000,
        "stock": "Disponible",
        "description": "Gorra Gymshark blanca con ajuste personalizado. Combina estilo y funcionalidad, ideal para completar tu look deportivo y protegerte del sol durante tus entrenamientos.",
        "imgsecundary": "img/Gorragymshark2B.jpeg",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "Color Blanco",
        "talla": ["Unica"],
        "categories": ["PROMOCION", "ACCESORIOS", "GYMSHARK", "GORRAS"]
    },
    {
        "_id": 6,
        "name": "DUO DEPORTIVO NIKE",
        "imgprincipalUrl": "img/duoslicralarga.png",
        "price": 11000,
        "pricepromo": 9000,
        "stock": "Disponible",
        "description": "Duo deportivo Nike en licra larga, disponible en diferentes opciones de color. Hecho de tela brush, ofrece comodidad y ajuste perfecto para tus actividades físicas.",
        "imgsecundary": "img/pantaAzul.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "LICRA LARGA S M L",
        "talla": ["S", "M", "L"],
        "categories": ["PROMOCION", "DUOS DEPORTIVOS", "NIKE", "MUJER"]
    },
    {
        "_id": 7,
        "name": "DUO OVERZIZE pink BIKER",
        "imgprincipalUrl": "img/bikerduorosado.png",
        "price": 12000,
        "pricepromo": 10000,
        "stock": "Disponible",
        "description": "Duo deportivo licra biker rosado, hecho de tela brush. Perfecto para quienes buscan estilo y confort en sus entrenamientos.",
        "imgsecundary": "img/duoslicralarga.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "S M L",
        "talla": ["S", "M", "L"],
        "categories": ["PROMOCION", "DUOS DEPORTIVOS", "MUJER"]
    },
    {
        "_id": 8,
        "name": "PANTALONETA NAUTICA W",
        "imgprincipalUrl": "img/Pantablanca.png",
        "price": 12000,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Pantaloneta náutica blanca, hecha de tela buz. Disponible en tallas S, M y L, ideal para actividades acuáticas y deportivas.",
        "imgsecundary": "img/pantaAzul.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "COLOR BLANCO",
        "talla": ["S", "M", "L"],
        "categories": ["PANTALONETAS", "HOMBRE"]
    },
    {
        "_id": 9,
        "name": "PANTALONETA HUGO BOSS",
        "imgprincipalUrl": "img/pantaAzul.png",
        "price": 12000,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Pantaloneta azul Hugo Boss, hecha de tela buz. Disponible en tallas S, M y L, perfecta para un look elegante y cómodo durante tus actividades.",
        "imgsecundary": "img/duoslicralarga.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "AZUL",
        "talla": ["S", "M", "L"],
        "categories": ["PANTALONETAS", "HOMBRE"]
    },
    {
        "_id": 10,
        "name": "PANTALONETA NAUTICA AZUL",
        "imgprincipalUrl": "img/pantaNauticaazul.png",
        "price": 12000,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Pantaloneta náutica azul, hecha de tela buz. Disponible en tallas S, M y L, ideal para quienes buscan comodidad y estilo en actividades acuáticas.",
        "imgsecundary": "img/Pantablanca.pngg",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "AZUL",
        "talla": ["S", "M", "L"],
        "categories": ["PANTALONETAS", "HOMBRE"]
    },
    {
        "_id": 11,
        "name": "PANTALONETA NIKE NEGRA",
        "imgprincipalUrl": "img/pantaNikenegra.png",
        "price": 12000,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Pantaloneta Nike negra hecha de tela buz, disponible en tallas S, M y L. Ideal para actividades deportivas y para aquellos que buscan un look elegante y cómodo.",
        "imgsecundary": "img/pantanegra2.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "NEGRO",
        "talla": ["S", "M", "L"],
        "categories": ["PANTALONETAS", "HOMBRE"]
    },
    {
        "_id": 12,
        "name": "SET NIKE BLANCO 8P",
        "imgprincipalUrl": "img/setnikeblanco.png",
        "price": 20000,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Set Nike blanco de 8 piezas, fabricado con tela buz. Disponible en tallas S, M y L, este set ofrece un ajuste perfecto y es ideal para quienes buscan estilo y comodidad en sus entrenamientos.",
        "imgsecundary": "img/duoslicralarga.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "BLANCO",
        "talla": ["S", "M", "L"],
        "categories": ["SETS", "MUJER", "NIKE"]
    },
    {
        "_id": 13,
        "name": "FALDA DEPORTIVA NIKE NARANJA",
        "imgprincipalUrl": "img/FaldaDepNN.png",
        "price": 10900,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Falda deportiva Nike en color naranja, hecha de tela buz. Disponible en tallas S, M y L, es perfecta para quienes buscan un diseño deportivo y cómodo.",
        "imgsecundary": "img/setnikeblanco.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "NARANJA",
        "talla": ["S", "M", "L"],
        "categories": ["FALDAS", "MUJER", "NIKE"]
    },
    {
        "_id": 14,
        "name": "FALDA DEPORTIVA NIKE VERDE",
        "imgprincipalUrl": "img/FaldaNV.png",
        "price": 10900,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Falda deportiva Nike en color verde, fabricada con tela buz. Disponible en tallas S, M y L, ofrece estilo y comodidad para tus entrenamientos.",
        "imgsecundary": "img/setnikeblanco.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "VERDE",
        "talla": ["S", "M", "L"],
        "categories": ["FALDAS", "MUJER", "NIKE"]
    },
    {
        "_id": 15,
        "name": "FALDA DEPORTIVA NIKE MORADA",
        "imgprincipalUrl": "img/FaldaNM.png",
        "price": 10900,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Falda deportiva Nike en color morado, hecha de tela buz. Disponible en tallas S, M y L, combina confort y diseño deportivo para tus actividades físicas.",
        "imgsecundary": "img/setnikeblanco.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "MORADO",
        "talla": ["S", "M", "L"],
        "categories": ["FALDAS", "MUJER", "NIKE"]
    },
    {
        "_id": 16,
        "name": "FALDA DEPORTIVA NIKE NEGRA",
        "imgprincipalUrl": "img/FaldaNN.png",
        "price": 10900,
        "pricepromo": 0,
        "stock": "Disponible",
        "description": "Falda deportiva Nike en color negro, hecha de tela buz. Disponible en tallas S, M y L, ideal para quienes buscan un diseño versátil y cómodo para el deporte.",
        "imgsecundary": "img/setnikeblanco.png",
        "tiempoEntrega": "3 DIAS",
        "gastoenvio": 3000,
        "valoracion": "⭐⭐⭐⭐⭐",
        "envio": ["Envio Postal", "Recogida en tienda"],
        "garantia": "1 MES",
        "subdescription": "NEGRO",
        "talla": ["S", "M", "L"],
        "categories": ["FALDAS", "MUJER", "NIKE"]
    }

]